### ISSUE TITLE
Merge fix for closing database from cordova-sqlite-storage repo

### ISSUE THREAD

**Issue by jacobg** [brodysoft/cordova-sqlite-evcore-extbuild-free#49]
Commit:
https://github.com/xpbrew/cordova-sqlite-storage/commit/70eaa9d5acbefaf9faff0489165cb69bb200a4cd

Issue:
https://github.com/xpbrew/cordova-sqlite-storage/issues/833

**Comment by brodybits** [comment]
This should be merged now. Please report if it is still missing in the latest release.
